### ISSUE TITLE
Framework should only contain Redacted API Keys, and not the functionality

### ISSUE THREAD

**Issue by kunalverma25** [getappbox/AppBox-iOSAppsWirelessInstallation#161]
The MailGun, TinyURL etc functionality is also inside the framework, So developers cannot extend and/or change that functionality. Which kinda diminishes the whole purpose of open-sourcing. Personally I think, only the keys should be redacted and not the functionality, so if some dev wants to extend the functionality, they can do so easily.

**Comment by vineetchoudhary** [comment]
Hi, that doesn't make any sense because anyone can access those keys and misuse them. 

I'm thinking a different way, I'll open source that private framework without any key. Where user can rebuild that framework with their own key.

**Comment by kunalverma25** [comment]
Yeah.. Maybe a different branch, without the keys?

**Comment by kunalverma25** [comment]
@vineetchoudhary Any estimated when, you'll be able to add this?
Btw.. Thanks for such an awesome project!

**Comment by vineetchoudhary** [comment]
Hi, I can't promise. But I'll surely work on it. I already have a few things to plan for this.


- [Shared variables for Fastlane plugin](https://github.com/getappbox/fastlane-plugin-appbox/issues/3)
- [iOS SDK](https://github.com/getappbox/AppBox-iOS-SDK)
- [Xamarin SDK](https://github.com/getappbox/AppBox-Xamarin-SDK)
- [Manual Signing](https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/issues/160)

After these, I'll work on this.
