### ISSUE TITLE
Can't able to find file/folder.

### ISSUE THREAD

**Issue by kladis** [getappbox/AppBox-iOSAppsWirelessInstallation#174]
Hello.

I have a list of files in the dashboard. How to remove some of them from the list? Probably they was actually removed somehow -> my dropbox folder is empty. 
"Show in Finder" button gives "File not found" error.
"Delete build" geves the subject error.

The list of dead items in the dashboard misleads...

Thanks in advance. Your tool is perfect anyway!

**Comment by kladis** [comment]
UPD: Mac OS. 
Latest version of your tool. But the issue happened with some older version probably.
And probably related with "keep same link" once was checked.

Maybe it's possible to find "property list" on my computer and remove the items manually? Or something like this kind of cleaning... list of strings.

**Comment by vineetchoudhary** [comment]
- If "Show in Finder" gives "File not fount" error that means build files no longer present in your system. (You've deleted the build files manually from your system)
- If "Delete build" gives an error that means build files no longer present in your dropbox account. (You've deleted the build files manually from Dropbox)
- If you are using "Keep same link" feature and delete a build from AppBox that'll only remove the selected version from your Dropbox account and any other version of the same build would not get affected.

----

I also think all these options misleads but there is a lot of work I need to do If I want to sync dashboard with Dropbox account. So, a better option is, do not delete build directly from the dropbox use AppBox Dashboard to delete the build from Dropbox.

So, I'll keep this issue open. I'll try to figure out some simple way to the cleanup AppBox Dashboard.

Thank you. Have a nice day :)

**Comment by gb160** [comment]
Is there any way to clean up manually?
Edit a file somewhere?

Its really annoying having old IPAs in the dashboard that don't exist, although I'll admit its all my own doing.

Great app btw.

**Comment by kimalive** [comment]
Is there still no manual way to cleanup and remove bad items from the Dashboard.

**Comment by vineetchoudhary** [comment]
Hi,

I know it is a long time. but finally, with the [latest release](https://github.com/getappbox/AppBox-iOSAppsWirelessInstallation/releases/latest), we have an option to delete builds from the dashboard only. Now we have an option called "Delete only from Dashboard" which will delete the build record from the AppBox local database.

<img width="966" alt="Screenshot 2022-05-08 at 1 43 03 PM" src="https://user-images.githubusercontent.com/8479436/167290278-78dca39d-4ff9-4977-8c38-320523cf9790.png">
