### ISSUE TITLE
Show Dropbox Account Info

### ISSUE THREAD

**Issue by jitheshdv** [getappbox/AppBox-iOSAppsWirelessInstallation#200]
It would be great if we can see the logged-in Dropbox account details, like Name and Email in the Accounts Menu.
![image](https://user-images.githubusercontent.com/60887306/91218417-a32b5e00-e736-11ea-9ad9-e454f50769b3.png)

**Comment by vineetchoudhary** [comment]
Hi, Thank you for your feedback. I'll add this in the new release.

**Comment by vineetchoudhary** [comment]
Hi,

In the [latest release](https://github.com/getappbox/AppBox-iOSAppsWirelessInstallation/releases/latest), I've added the currently logged-in user display name and email id to the Accounts menu. 

<img width="737" alt="Screenshot 2022-05-08 at 1 09 03 PM" src="https://user-images.githubusercontent.com/8479436/167290388-67252efc-df2e-4074-a7bf-de9a5579b831.png">
