### ISSUE TITLE
Failed to open zip file

### ISSUE THREAD

**Issue by cgtyky** [getappbox/AppBox-iOSAppsWirelessInstallation#208]
## Description
I can not upload using AppBox. When I try the only thing I get is an error that says "failed to open zip file". I am not trying to upload a zip file. I tried using an Xcode project. It builds using the schema but after finishing building it gave me the same error. One time it stuck at the "Checking IPA file" phase for over 60 hours. My IPA is rather big (around 10 GB). My predecessor in my position managed to do it with AppBox. AppBox sees my Dropbox account and gives correct storage values. I tried with different Macs with different MacOS versions but got the same result.

## Steps to Reproduce
1. Drag and drop IPA file or choose an IPA file or choose an Xcode project
2. Click Upload.

## Details
1. Which AppBox version are you using?
    - [X] 2.9.1
    - [ ] 2.7.2
    - [ ] 2.7.1
    - [ ] 2.7.0
    - [ ] 2.6.1
    - [ ] 2.6.0
    - [ ] 2.5.0
    
2. Which macOS version did you experience the issue on?
    - [X] macOS 11.2.1
    - [X] macOS 11.0.1
    - [X] macOS 10.15.2
    - [ ] macOS 10.14.x
    - [ ] macOS 10.13.x
    - [ ] macOS 10.12.x
    - [ ] macOS 10.11.x
    - [ ] macOS 10.10.x

4. Screenshots

![image](https://user-images.githubusercontent.com/8817945/109471091-53c94000-7a81-11eb-9c75-b8fa0b6962d7.png)

## AppBox Logs
<details>
  <summary><b>Logs</b></summary>
  <pre><code>
  DropBox Used Space : 91281MB
  DropBox Available Space : 3147776MB
  Extracting Files...
  ALERT -
  Title - AppBox - Error Message - failed to open zip file
  Extracting Files...
  ALERT -
  Title - AppBox - Error Message - failed to open zip file
  Extracting Files...
  ALERT -
  Title - AppBox - Error Message - failed to open zip file
  Extracting Files...
  ALERT -
  Title - AppBox - Error Message - failed to open zip file
  Extracting Files...
  ALERT -
  Title - AppBox - Error Message - failed to open zip file
  </code></pre>
</details>

**Comment by vineetchoudhary** [comment]
Hi, Sorry for the late reply. I'm able to upload a test build of over 10 GB (included some random video files to increase the IPA size). Can you share your build file so I can test it with your IPA file? If you have enterprises IPA you can send it by removing the provisioning profile.

You can share a dropbox or google drive link on my email id. vineetchoudhary[at]live.in

**Comment by vineetchoudhary** [comment]
This issue has been closed because there has been no response to our request for more information from the author. With only the information that is currently on the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.
