### ISSUE TITLE
IPA Signing with Free Developer Account

### ISSUE THREAD

**Issue by ParthJadhav** [getappbox/AppBox-iOSAppsWirelessInstallation#221]
There's always been limitations for installing Third-Party IPA's on iOS with the free developer account.

I was wondering if there is a way to install Third-Party IPA's bypassing the Free 3 Apps (Using Provision certificate) Limit. Also without jailbreak.

One way is to get an Enterprise Certificate from outer sources, But It's almost impossible to find one for free. 

I saw that AppBox says it has AutoSigning Feature but I didn't find it on the app or maybe it's same like the AltStore.

Because after I install a App after 3 Apps limit it's showing that - 
Unable to install the app.

Any Help would be appreciated.

**Comment by AlissonRS** [comment]
@vineetchoudhary not sure if related, sorry I have zero experience with XCode/Apple stuff, but in order to generate an IPA and upload to AppBox, do I need a paid Apple Developer Account so the app can be archived/signed?

**Comment by vineetchoudhary** [comment]
Hi @AlissonRS , 

Yes. You can build and run the app with a free apple developer account. It is limited to your local devices only. Like you can connect your iPhone or iPad with a mac to run and test the application.

But if you want to distribute the app via any medium AppStore, Testflight, AppBox, etc. then you will need an apple account.

**Comment by AlissonRS** [comment]
@vineetchoudhary thanks for your fast reply. Seems like this Apple Account is a bit expensive, and since my app is based on a PWA (html5), I'll rarely need to rebuild the iOS app (e.g I don't need it for the entire year). Do you know if there are other ways I can sign my app (generate IPA) for an ad-hoc build? Maybe a paid service that allows an ad-hoc signing?

**Comment by vineetchoudhary** [comment]
Hi, Without paid Apple Developer Account we can not sign an iOS Application. There is no other paid/free service which can do the same.

**Comment by AlexByte** [comment]
@vineetchoudhary what about signulous.com?
