### ISSUE TITLE
Checking IPA File phase refers to scheme name, not to PRODUCT_BUNDLE_IDENTIFIER identifier

### ISSUE THREAD

**Issue by degtiarev** [getappbox/AppBox-iOSAppsWirelessInstallation#230]
The app creates IPA file with name of PRODUCT_BUNDLE_IDENTIFIER. But when the app checks IPA file, it uses name of scheme to find it.

`Checking IPA File...
Finding IPA file at path - ${path_to_compiled_file}/${scheme_name}.ipa
Not able to find IPA file at path -  ${path_to_compiled_file}/${scheme_name}.ipa
`

**Comment by vineetchoudhary** [comment]
Hi, I've removed the Build project/workspace part from the AppBox. Because more than 98% of users only use AppBox to upload the IPA file directly. This issue is no longer valid with the latest release.
