### ISSUE TITLE
Appbox is not opening , Please Please Resolve

### ISSUE THREAD

**Issue by ShambhooSevenstar** [getappbox/AppBox-iOSAppsWirelessInstallation#232]
## Steps to Reproduce
1.
2.

## Details

1. Which AppBox version are you using?
    - [ ] 2.7.2
    - [ ] 2.7.1
    - [ ] 2.7.0
    - [ ] 2.6.1
    - [ ] 2.6.0
    - [ ] 2.5.0
    

2. Which macOS version did you experience the issue on?
    - [ ] macOS 10.14.x
    - [ ] macOS 10.13.x
    - [ ] macOS 10.12.x
    - [ ] macOS 10.11.x
    - [ ] macOS 10.10.x
   
3. Crash Report

```
<!-- If you have the crash report, then please copy paste that here otherwise remove this option. -->
```

4. Screenshots

## AppBox Logs
<details>
  <summary><b>Logs</b></summary>
  <pre><code>
  
  </code></pre>
</details>

**Comment by degtiarev** [comment]
The app just to crash on start. I noticed this behaviour today, but it worked a week ago.

**Comment by ELapkovskaja** [comment]
Same situation

**Comment by vineetchoudhary** [comment]
Hi, I'm aware of this issue. Apple blocked our Developer Account which we used to sign the AppBox with Developer ID certificate. So, I'm working on it. For now, I'll upload an unsigned version of AppBox today.

**Comment by vineetchoudhary** [comment]
Please download the new version signed with the new Apple Developer Account - https://github.com/getappbox/AppBox-iOSAppsWirelessInstallation/releases/tag/2.9.6.

To avoid this in the future, I'm planning to maintain an AppStore version of AppBox without the Build feature. So, with the AppStore version, you can upload the IPA file to your Dropbox account.
