### ISSUE TITLE
Appbox: Version 2.9.1 is not working 

### ISSUE THREAD

**Issue by foramr** [getappbox/AppBox-iOSAppsWirelessInstallation#233]
## Description
Version 2.9.1 is not working 

## Steps to Reproduce
1. Open App box and it say's can't open and then crash report

## Details
1. Which AppBox version are you using?
    - [X] 2.9.1
   
2. Which macOS version did you experience the issue on?
    - [X] macOS 12.0.1

3. Crash Report
Incident Identifier: 86E611D1-7A6B-4DD1-9518-906E8CC238B7
CrashReporter Key:   6E1985F5-C069-71A6-A10F-C78174E55159
Hardware Model:      MacBookPro15,4
Process:             AppBox [97966]
Path:                /Applications/AppBox.app/Contents/MacOS/AppBox
Identifier:          com.developerinsider.AppBox
Version:             2.9.5 (1)
Code Type:           X86-64 (Native)
Role:                Default
Parent Process:      launchd [1]
Coalition:           com.developerinsider.AppBox [8396]

Date/Time:           2022-01-18 16:13:26.7500 +0530
Launch Time:         2022-01-18 16:13:26.6446 +0530
OS Version:          macOS 12.0.1 (21A559)
Release Type:        User
Report Version:      104

**Comment by vineetchoudhary** [comment]
@foramr Please use the latest version of AppBox 2.9.6. For more details check this issue - https://github.com/getappbox/AppBox-iOSAppsWirelessInstallation/issues/232
