### ISSUE TITLE
Share URL page opening with error

### ISSUE THREAD

**Issue by yuvirajsinh** [getappbox/AppBox-iOSAppsWirelessInstallation#234]
## Describe the bug
Not able to access any builds uploaded through AppBox. Share URL page opens with error.

## To Reproduce
1. Upload any build through AppBox
2. Open Share URL on Safari
3. See this error: "Uh oh! We couldn't load application information! Please make sure you are connected to the Internet or dropbox.com & dl.dropboxusercontent.com is not blocked and try again."

## Expected behavior
Share URL page should open with options to **Install latest** build or **Install previous builds**

## Screenshots
<img width="1792" alt="Screenshot 2022-02-01 at 12 02 27 PM" src="https://user-images.githubusercontent.com/7068799/151926615-205e93c1-5585-41e6-8c5c-67f01a7a2b88.png">

## Desktop (please complete the following information):
 - OS: macOS Big Sur
 - Browser Safari
 - Version 11.2.1

## Smartphone (please complete the following information):
 - Device: iPhone XR, iPhone 11
 - OS: iOS 13.5.1, 14.*, 15.*
 - Browser Safari

## Additional context
Facing this issue suddenly from today, it was working till yesterday

**Comment by kimalive** [comment]
I'm getting the same error and problem for all existing appbox links. Fails in destop browsers and on iPhone with the same error.

**Comment by radubogdan2k** [comment]
+1, I'm having the same issue on all my apps

**Comment by akkalbhor** [comment]
Same Issue for me as well.

**Comment by vineetchoudhary** [comment]
Hi All, 

There are some breaking changes from Dropbox. Now Dropbox no longer allows Cross-Origin requests which we used to fetch build information on `web.getappbox.com`.  When you try to open your build installation web page you will see something like this on your web console - 

> Access to XMLHttpRequest at 'https://dl.dropboxusercontent.com/s/y5XXXXXXXXXXXXp/appinfo.json' from origin 'https://web.getappbox.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Right now I think a proxy server will help us to make AppBox work again. So, I'm working on it and keep you guys updated.

**Comment by radubogdan2k** [comment]
@vineetchoudhary Thanks for the quick response!

**Comment by vineetchoudhary** [comment]
Hi Everyone,

Just created a proxy server on Heroku for a temporary time to make AppBox Web work. Now you can see all `dl.dropboxusercontent.com` request is going through the Heroku proxy server  `appbox-proxy-server.herokuapp.com`. So, with this proxy server, all our existing apps will work as it is.

As this proxy server is now life line of AppBox, I'll move this proxy server to a more stable place like on AWS or Azure with some high availability so we can have this up 24x7.

Let me know if you guys still facing some issues.

**Comment by radubogdan2k** [comment]
Working great for me, thank you!

P.S. I think Heroku is already hosted on AWS

**Comment by vineetchoudhary** [comment]
Yes @radubogdan2k. But I think Heroku doesn't provide a load balancer. I'm thinking like we can host two-three instances of this proxy server and then handle requests via a load balancer if one instance dies then another one can handle the requests. Also, some of our users create huge requests on AppBox Web at a same period of time (like for a day). So, multiple instances can handle these requirements very easly.

**Comment by radubogdan2k** [comment]
@vineetchoudhary I'm assuming the iOS client is downloading the IPA directly from dropbox, right? I'm asking because earlier I only tested that the AppBox page is loading correctly but now actually trying to install the app (which is a few hundred MB), the iOS client is just staying on `Waiting...` for 10 minutes now instead of starting the `Loading` phase... just wondering if it's related to today's issue.

**Comment by vineetchoudhary** [comment]
iOS client directly accesses the manifest and IPA file from Dropbox. CORS policy only applies to Websites with different domain names. So, I don't think this is related to the CORS policy. I just tested and the app installation is working fine. Can you please check the app signing things like provisioning profile, certificate etc...

**Comment by radubogdan2k** [comment]
@vineetchoudhary It unblocked by itself after 25-30 minutes. Weird, no idea why the delay. Anyway, all good now, thanks again for the quick fix!
