### ISSUE TITLE
Started getting error "Unable to install [APPNAME]. Please try again later." all of a sudden

### ISSUE THREAD

**Issue by radubogdan2k** [getappbox/AppBox-iOSAppsWirelessInstallation#235]
## Describe the bug
I didn't make any recent changes to the uploaded IPA files but all of a sudden, installation via appbox website is no longer working. The attached message is showing up immediately after tapping Install Application (the ipa file is several hundred MB in size and the error is appearing within 2-3 seconds, so it's definitely not downloading the app).

I double checked the UDID of the device is present in the provisioning profile.
I dragged the IPA file directly into the `Devices` window of XCode and it installed on the device without problems.

Is this a known issue? Are there any checks performed before download that could trigger this error?

Thank you.

![IMG_1230](https://user-images.githubusercontent.com/86427194/155486937-8e67754a-f163-4381-98ed-85ce7488dc1a.jpg)

**Comment by vineetchoudhary** [comment]
Hi @radubogdan2k, AppBox doesn't handle anything once we tap on the install button. AppBox just kind of handover the manifest file URL to the iOS itms-service and now it is iOS responsibility to install the app. However there might be some issue with the manifest URL or IPA file URL so, I'll check that. 

I also received a message from another developer facing the same issue this morning but I'm able to use and install all my apps normally. 

So, I'll debug this today and try to fix this. For now, can you please tell me device details like iOS version, device name?

Also, can you access dropbox from that device?

**Comment by radubogdan2k** [comment]
Hi,

Thanks for looking into it. I'm testing on an iPad Pro 2018 and an iPhone 12 Pro Max, both on latest iOS (15.3.1). There were no changes to my devices or to the apps since a few days ago when everything was working fine. Both devices have internet connection and can access dropbox.

One of the apps, after several retries, eventually worked. After that, it stopped working again. No idea what's going on

**Comment by vineetchoudhary** [comment]
Hi,

Currently, all dropbox services are under scheduled maintenance. So, Apps installation is not working due to this. Dropbox direct download service returning 500 HTTP status code. Please check the latest status of Dropbox services here - https://status.dropbox.com/incidents/w9m77dlthdmy



<img width="935" alt="Screenshot 2022-02-24 at 6 10 13 PM" src="https://user-images.githubusercontent.com/8479436/155526153-e83d3088-b0be-4dc8-9e99-33f98646b2db.png">

**Comment by radubogdan2k** [comment]
@vineetchoudhary "Dropbox direct download service returning 500 HTTP status code" - is this something you were able to confirm on your end?

**Comment by vineetchoudhary** [comment]
Yes. Just debug it on the iOS device and also on the web client it is returning 500.

<img width="1451" alt="Screenshot 2022-02-24 at 6 22 07 PM" src="https://user-images.githubusercontent.com/8479436/155527494-77514483-719a-4e01-9f37-742aff4fa12f.png">


You can also check on an iOS device by connecting to a mac and stream device log to the mac console application. Then search for dropbox in the log.

**Comment by radubogdan2k** [comment]
@vineetchoudhary Understood, thank you!

**Comment by radubogdan2k** [comment]
@vineetchoudhary is it possible with appbox to host apps on a private server?

**Comment by vineetchoudhary** [comment]
Not right now. But that is something I've planned as recent continues breaking changes from Dropbox.

**Comment by radubogdan2k** [comment]
Yes, that's exactly why I asked. I would prefer to move everything on a private server and not depend on Dropbox anymore...

**Comment by vineetchoudhary** [comment]
All dropbox systems are now operational. Everything should work as expected let me know if you guys are still facing some issues. https://status.dropbox.com/

<img width="895" alt="Screenshot 2022-02-26 at 10 16 04 AM" src="https://user-images.githubusercontent.com/8479436/155829742-c8930873-0a9e-42c7-88a8-e9a98c5d146b.png">
