### ISSUE TITLE
Can't upload any IPA

### ISSUE THREAD

**Issue by amithacoon** [getappbox/AppBox-iOSAppsWirelessInstallation#251]
## Description
im droping an IPA as usual but it gives me error # 409

## Details
1. Are you using the latest version?
    - [ ] Yes. I'm using the latest version.
    

2. Which macOS version did you experience the issue on?
    - macOS 12.3.0
   
3. Crash Report

```
<!-- If you have the crash report, then please copy paste that here otherwise remove this option. -->
```

4. Screenshots
<img width="275" alt="image" src="https://user-images.githubusercontent.com/59620062/190844420-e99bd0f7-e594-4944-b280-0ca9d7235404.png">
## AppBox Logs
<details>
  <summary><b>Logs</b></summary>
  <pre><code>
  
  </code></pre>
</details>

**Comment by vineetchoudhary** [comment]
Hi, I'm not facing this issue. Can you please try to logout and login again to your dropbox account?

If this doesn't fix the issue and you've previously uploaded this build on dropbox then delete that IPA file and other metadata from dropbox and try to upload again.

**Comment by vineetchoudhary** [comment]
This issue has been closed because there has been no further response from the author. If the above solution doesn't work, please reach out so that we can investigate further.
