### ISSUE TITLE
Unlink Dropbox Account

### ISSUE THREAD

**Issue by hackspeedok09** [getappbox/AppBox-iOSAppsWirelessInstallation#252]
Hi there, how can I unlink Dropbox Account ? Thanks

**Comment by vineetchoudhary** [comment]
Hi, you can disconnect AppBox from your Dropbox Account Settings. https://www.dropbox.com/account/connected_apps

<img width="1628" alt="Screenshot 2023-04-17 at 8 24 09 AM" src="https://user-images.githubusercontent.com/8479436/232366911-9f9ac914-31e9-476b-8a3e-0d8c631c1294.png">
