### ISSUE TITLE
I'm not sure where to put this, so here goes.

### ISSUE THREAD

**Issue by Dan2TDMJace** [getappbox/AppBox-iOSAppsWirelessInstallation#254]
So, I'm in developer mode. When I try to install an app, it says this. (Pictured below)
![IMG_0310](https://github.com/getappbox/AppBox-iOSAppsWirelessInstallation/assets/112831108/9c3df3b8-6feb-4cd4-9dfe-092a71db2e30)
No one else seems to have this problem. I'm in Developer Mode and there are no profiles showing. I don't know why.

**Comment by vineetchoudhary** [comment]
Hi, there might be multiple reasons for this popup. But please check this device id is present in your app provisioning profile. Putting your device in developer mode is not enough to install an application.

As you mentioned no one else has this problem which also suggests that the device id is missing from the provisioning profile. Please contact the person who created the build.
