### ISSUE TITLE
AppBox version 2.9.6, build URL Shows "The app you were looking for is not available anymore. It might has been deleted. Please refer to your app developer for any question."

### ISSUE THREAD

**Issue by sumitaggarwal23021999** [getappbox/AppBox-iOSAppsWirelessInstallation#256]
## Steps to Reproduce
1.
2.

## Details
1. Are you using the latest version?
    - [ ] Yes. I'm using the latest version.
    

2. Which macOS version did you experience the issue on?
    - macOS 12.3.0
   
3. Crash Report

```
<!-- If you have the crash report, then please copy paste that here otherwise remove this option. -->
```

4. Screenshots

## AppBox Logs
<details>
  <summary><b>Logs</b></summary>
  <pre><code>
  
  </code></pre>
</details>

**Comment by sumitaggarwal23021999** [comment]
After uploading IPA I get a URL and when trying to open that URL I am getting "The app you were looking for is not available anymore. It might has been deleted. Please refer to your app developer for any question." this error, even if I haven't deleted the build.
<img width="1440" alt="Screenshot 2023-06-05 at 5 24 21 PM" src="https://github.com/getappbox/AppBox-iOSAppsWirelessInstallation/assets/52203085/5be5382d-c20b-4f29-a969-4e69ff9e0d1c">

Also I tried to check with latest version of AppBox but it always shows "Invalid URL. Please double-check your app URL.".
<img width="1403" alt="Screenshot 2023-06-05 at 5 23 51 PM" src="https://github.com/getappbox/AppBox-iOSAppsWirelessInstallation/assets/52203085/f628afb1-9089-461e-969a-4aac992f0bee">

Please look into it.

**Comment by sumitaggarwal23021999** [comment]
There was some issue in my dropbox account, So I deleted my current account and recreated one.

**Comment by vineetchoudhary** [comment]
If anyone else facing the same issue please discuss it here - https://github.com/getappbox/AppBox-iOSAppsWirelessInstallation/issues/255
