### ISSUE TITLE
invalid URL. Please double check your app url

### ISSUE THREAD

**Issue by BodyBookApps** [getappbox/AppBox-iOSAppsWirelessInstallation#257]
https://web.getappbox.com/?url=/scl/fi/e7vfjq8f1etqh8inm7fwy/appinfo.json?dl=0&rlkey=wrdq1fcd4cxolwwdtu58

**Comment by vineetchoudhary** [comment]
Hi

Dropbox made some changes in URL sharing permissions. Please logout and login again to resolve the issue. If that doesn't work try to login with another account. 

I'm going to close this issue. Please discuss this here -  https://github.com/getappbox/AppBox-iOSAppsWirelessInstallation/issues/255
