### ISSUE TITLE
invalid URL. Please double check your app url message is coming up when  the install link is clicked 

### ISSUE THREAD

**Issue by BodyBookApps** [getappbox/AppBox-iOSAppsWirelessInstallation#258]
## Description
Hello I am getting this message: invalid URL instead of getting the usual   dl.dropbox  

## Steps to Reproduce
1.
2.

## Details
1. Are you using the latest version?
    - [x] Yes. I'm using the latest version.
    

2. Which macOS version did you experience the issue on?
    - macOS 12.3.0
   
3. Crash Report

```
<!-- If you have the crash report, then please copy paste that here otherwise remove this option. -->
```

4. Screenshots

## AppBox Logs
<details>
  <summary><b>Logs</b></summary>
  <pre><code>
  
  </code></pre>
</details>

**Comment by BodyBookApps** [comment]
macOS  Ventura 13.3.0

**Comment by BodyBookApps** [comment]
1) the following did not appear:  And it is not applicable because the app did not go to app store as of now 
If the iOS popup "dl.dropboxusercontent.com would like to install ... " did not appear, check that you don't already have the same app installed from the AppStore.
If an app with the same bundle identifier is already installed on the device from the AppStore, nothing will happen.
2) Nothing seems to happen ... Yes nothing is happening and no install is happening ..  the appbox shows a message invalid URL  
After tapping the "Install" button in the popup, if nothing seems to happen and you are on this page, check your device's home screen: the installation should be in progress: you should see the icon of the app somewhere and a progress indicator.

**Comment by vineetchoudhary** [comment]
Hi

Dropbox made some changes in URL sharing permissions. Please logout and login again to resolve the issue. If that doesn't work try to login with another account. 

I'm going to close this issue. Please discuss this here -  https://github.com/getappbox/AppBox-iOSAppsWirelessInstallation/issues/255

**Comment by BodyBookApps** [comment]
Hello Vineet, 
Thank you for your response. However I may want to know  this information. My colleague  did not experience any issue uploading the IPA file for the same app. If the Dropbox changed the link as you stated, the. I like to know why the change did not impact my college. 
Hope you can dig more into this. This happened suddenly without any changes on my part. 
Thank you so much. 

Purna Movva 
Manager, Apps Development. 
BodyBookApps

**Comment by BodyBookApps** [comment]
With Spelling corrections

**Comment by vineetchoudhary** [comment]
Hi, Dropbox doesn't roll out these kinds of changes to every user at the same time. They'll roll out in phases. Right now, looks like they roll out these changes to a few-year-old customer. If someone has an old account (like a 5-year-old account) they are still able to generate old-format share links.

**Comment by BodyBookApps** [comment]
Vineet,Thank you for explaining why the problem does not occur to all at the same time. The message display on the ApoBox  ‘invalid url’ is very cryptic. It would be useful if you can expand the msg to explain  how to fix the issue. It took us a very long time to isolate the problem.  Request you to consider this suggestion that would save time for lots of people if implemented. Purna Movva Sent from my iPhoneOn Jun 14, 2023, at 12:13 AM, Vineet Choudhary ***@***.***> wrote:﻿
Hi, Dropbox doesn't roll out these kinds of changes to every user at the same time. They'll roll out in phases. Right now, looks like they roll out these changes to a few-year-old customer. If someone has an old account (like a 5-year-old account) they are still able to generate old-format share links.

**Comment by vineetchoudhary** [comment]
I'm still waiting for the final reply from the Dropbox team. Please keep an eye on this issue for more details - https://github.com/getappbox/AppBox-iOSAppsWirelessInstallation/issues/255
